name: GitHub Actions PR
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  PR-Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🔎 Your repository is ${{ github.repository }}, you are on branch is ${{ github.ref }} and your commit ref is ${{ github.head_ref }}.${{ github.sha }}."
      - name: Use correct node version
        uses: actions/setup-node@v4
        with:
            node-version: 'node'
            cache: 'npm'
            cache-dependency-path: ../../desktop-app/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ../../desktop-app/
      - name: Run unit tests
        id: unit-tests-run
        run: npm test
        working-directory: ../../desktop-app/
      - run: echo "Job is not failed"
